/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica6;

/**
 *
 * @author marco
 */
public class Ingreso extends javax.swing.JFrame {

    public static Lista listaUsuario = new Lista();
    public static Usuario u;
    
    public Ingreso() {
        initComponents();
        this.setLocationRelativeTo(null);
        crearUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelIngreso = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        labelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelIngreso.setText("Ingreso");
        jPanel1.add(labelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        labelUsuario.setText("Usuario");
        jPanel1.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        labelContrasena.setText("Contraseña");
        jPanel1.add(labelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 160, -1));
        jPanel1.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 160, -1));
        jPanel1.add(labelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
            
        String usuario = txtUsuario.getText();
        String contrasena = txtContrasena.getText();
       // Usuario usuarioEncontrado = listaUsuario.buscarUsuario(usuario);
        boolean usuarioEncontrado = false;
        
            Nodo nodoActual = listaUsuario.getPrimero();
                while (nodoActual != null) {
                    Usuario u = nodoActual.getUsuario();
                    if (u.getUsuario().equals(usuario) && u.getContrasena().equals(contrasena)) {
                      Registro registro = new Registro(this);
                      registro.setVisible(true);
                      this.setVisible(false);
                      usuarioEncontrado = true;
                       break;
                    }
                    nodoActual = nodoActual.getSiguiente();
                    
                }
                if(!usuarioEncontrado){
                    labelMensaje.setText("Cuenta incorrecta");
                }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void crearUsuarios(){
        
        Usuario usuario1 = new Usuario("Marco", "123");
        Usuario usuario2 = new Usuario("Antonio", "456");
        Usuario usuario3 = new Usuario("Jose","123");
        Usuario usuario4 = new Usuario("David","456");
        Usuario usuario5 = new Usuario("Diaz","123");
        
        listaUsuario.agregarUsuario(usuario1);
        listaUsuario.agregarUsuario(usuario2);
        listaUsuario.agregarUsuario(usuario3);
        listaUsuario.agregarUsuario(usuario4);
        listaUsuario.agregarUsuario(usuario5);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelIngreso;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
