/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica6;

/**
 *
 * @author marco
 */
public class Registro extends javax.swing.JFrame {
    
    public static Ingreso ing;
    public static Lista list = new Lista();
    public static short cantDias;
    public static double mensualidad;
    public static double destinoTuristico;
    public static double tipoHabitacion;
            
    public Registro(Ingreso ing) {
        initComponents();
        this.setLocationRelativeTo(null);
        Registro.ing = ing;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelRegistro = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        labelCantDias = new javax.swing.JLabel();
        labelMensualidad = new javax.swing.JLabel();
        labelDestinoTuristico = new javax.swing.JLabel();
        labelTipoHabitacion = new javax.swing.JLabel();
        labelTipoPago = new javax.swing.JLabel();
        cbTipoPago = new javax.swing.JComboBox<>();
        rbtnSuite = new javax.swing.JRadioButton();
        rbtnDoble = new javax.swing.JRadioButton();
        rbtnSencilla = new javax.swing.JRadioButton();
        sbCantidadDias = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDestinoTuristico = new javax.swing.JList<>();
        sbPagoMensualidad = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRegistro.setText("Registro");
        jPanel1.add(labelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        btnRegistrar.setText("Registro");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        labelCantDias.setText("Cantidad de dias");
        jPanel1.add(labelCantDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 70, 140, -1));

        labelMensualidad.setText("Pago de Mensualidad");
        jPanel1.add(labelMensualidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        labelDestinoTuristico.setText("Destino Turistico");
        jPanel1.add(labelDestinoTuristico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        labelTipoHabitacion.setText("Tipo de habitacion");
        jPanel1.add(labelTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        labelTipoPago.setText("Tipo de pago");
        jPanel1.add(labelTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        cbTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione--", "Paypal", "Visa", "MasterCard", "Pago en Oxxo" }));
        jPanel1.add(cbTipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 210, -1));

        buttonGroup1.add(rbtnSuite);
        rbtnSuite.setText("Suite");
        jPanel1.add(rbtnSuite, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        buttonGroup1.add(rbtnDoble);
        rbtnDoble.setText("Doble");
        jPanel1.add(rbtnDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        buttonGroup1.add(rbtnSencilla);
        rbtnSencilla.setText("Sencilla");
        jPanel1.add(rbtnSencilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        sbCantidadDias.setBlockIncrement(1);
        sbCantidadDias.setMaximum(30);
        sbCantidadDias.setMinimum(1);
        sbCantidadDias.setVisibleAmount(0);
        sbCantidadDias.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                sbCantidadDiasAdjustmentValueChanged(evt);
            }
        });
        jPanel1.add(sbCantidadDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 40, 270));

        listDestinoTuristico.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Puerto Vallarta", "Manzanillo", "Cancún", "Acapulco", "Los Cabos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listDestinoTuristico);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 350, 70));

        sbPagoMensualidad.setBlockIncrement(1);
        sbPagoMensualidad.setMaximum(30);
        sbPagoMensualidad.setMinimum(1);
        sbPagoMensualidad.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        sbPagoMensualidad.setVisibleAmount(0);
        sbPagoMensualidad.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                sbPagoMensualidadAdjustmentValueChanged(evt);
            }
        });
        jPanel1.add(sbPagoMensualidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 360, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        ing.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // Todo menos subtotal, iva, total a pagar
        // Es decir: Cantidad de dias, mensualidad, destino turistico, tipo habitacion y tipo pago
        
        String sTipoHabitacion = "";
        
        if(rbtnSuite.isSelected()){ sTipoHabitacion = "Suite";}
        else if(rbtnDoble.isSelected()){ sTipoHabitacion = "Doble";}
        else if(rbtnSencilla.isSelected()){ sTipoHabitacion = "Sencilla";}
        
        cantDias = (short) sbCantidadDias.getValue();
        
        switch(listDestinoTuristico.getSelectedIndex()){
            case 0: destinoTuristico = 500;
            case 1: destinoTuristico = 600;
            case 2: destinoTuristico = 700;
            case 3: destinoTuristico = 800;
            case 4: destinoTuristico = 900;
        }
        
        if(rbtnSuite.isSelected()){ tipoHabitacion = 500;}
        else if(rbtnDoble.isSelected()){ tipoHabitacion = 400;}
        else if(rbtnSencilla.isSelected()){ tipoHabitacion = 300;}
        
        
        list.agregarCotizacion(cantDias, mensualidad, destinoTuristico, tipoHabitacion,listDestinoTuristico.getSelectedValue(), sTipoHabitacion, String.valueOf(cbTipoPago.getSelectedItem()));
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed
 
    private void sbPagoMensualidadAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_sbPagoMensualidadAdjustmentValueChanged
        labelMensualidad.setText("Cantidad de bonos: "+String.valueOf(sbPagoMensualidad.getValue()));
        mensualidad = sbPagoMensualidad.getValue();
    }//GEN-LAST:event_sbPagoMensualidadAdjustmentValueChanged

    private void sbCantidadDiasAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_sbCantidadDiasAdjustmentValueChanged
        labelCantDias.setText("Cantidad de dias: "+String.valueOf(sbCantidadDias.getValue()));
        cantDias = (short) sbCantidadDias.getValue();
    }//GEN-LAST:event_sbCantidadDiasAdjustmentValueChanged

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        
        /*DefaultListModel model = (DefaultListModel)listDestinoTuristico.getModel();
        model.clear();*/
        
        sbCantidadDias.setValue(1);
        sbPagoMensualidad.setValue(1);
        buttonGroup1.clearSelection();
       listDestinoTuristico.setSelectedIndex(0);
       cbTipoPago.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        
        Mostrar most = new Mostrar(this, list);
        most.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro(ing).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipoPago;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCantDias;
    private javax.swing.JLabel labelDestinoTuristico;
    private javax.swing.JLabel labelMensualidad;
    private javax.swing.JLabel labelRegistro;
    private javax.swing.JLabel labelTipoHabitacion;
    private javax.swing.JLabel labelTipoPago;
    private javax.swing.JList<String> listDestinoTuristico;
    private javax.swing.JRadioButton rbtnDoble;
    private javax.swing.JRadioButton rbtnSencilla;
    private javax.swing.JRadioButton rbtnSuite;
    private javax.swing.JScrollBar sbCantidadDias;
    private javax.swing.JScrollBar sbPagoMensualidad;
    // End of variables declaration//GEN-END:variables
}
